name: Test conda install
on: [push]
jobs:
    test-conda-install:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: [3.8]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v1

            - name: Set up Python ${{ matrix.python-version }}
              uses: conda-incubator/setup-miniconda@v2
              with:
                auto-update-conda: true
                python-version: ${{ matrix.python-version }}

            - name: Update pip
              run: python -m pip install --upgrade pip

            - name: Install module
              run: python -m pip install .
